function animate_word_transformation(raw_word, dict_file)
% ANIMATE_WORD_TRANSFORMATION Renders a step-by-step visual animation in MATLAB
% showing raw OCR character assembly, dictionary matching, and meaningful word morphing.

    if nargin < 1 || isempty(raw_word)
        raw_word = 'മലയാള';
    end
    if nargin < 2 || isempty(dict_file)
        dict_file = 'malayalam_dictionary.txt';
    end

    % Run word corrector to get details
    [corrected_text, word_details] = weighted_word_corrector(raw_word, dict_file);

    if isempty(word_details) || isempty(word_details{1})
        msgbox('No word details found for animation.', 'Info');
        return;
    end

    details = word_details{1};

    % Initialize Figure
    fig = figure('Name', 'Animated Meaningful Word Transformation', ...
                 'NumberTitle', 'off', ...
                 'Color', [0.08, 0.09, 0.12], ...
                 'Position', [150, 150, 900, 550]);

    set(fig, 'MenuBar', 'none', 'ToolBar', 'none');

    % Header Title Panel
    uicontrol('Style', 'text', 'Parent', fig, ...
              'String', 'MALAYALAM OCR: MEANINGFUL WORD TRANSFORMATION', ...
              'Units', 'normalized', 'Position', [0.05, 0.88, 0.90, 0.08], ...
              'FontSize', 16, 'FontWeight', 'bold', ...
              'ForegroundColor', [0.35, 0.78, 1.0], ...
              'BackgroundColor', [0.08, 0.09, 0.12]);

    % Subtitle / Status
    hStatus = uicontrol('Style', 'text', 'Parent', fig, ...
              'String', 'Step 1: Assembling Raw Predicted Characters...', ...
              'Units', 'normalized', 'Position', [0.05, 0.82, 0.90, 0.05], ...
              'FontSize', 11, ...
              'ForegroundColor', [0.8, 0.8, 0.8], ...
              'BackgroundColor', [0.08, 0.09, 0.12]);

    % Panel 1: Raw Output Display
    hPanel1 = uipanel('Parent', fig, 'Title', ' Raw Predicted Characters ', ...
                      'FontSize', 11, 'ForegroundColor', [1 0.6 0.2], ...
                      'BackgroundColor', [0.12 0.14 0.18], ...
                      'Position', [0.05, 0.50, 0.42, 0.28]);

    hRawText = uicontrol('Style', 'text', 'Parent', hPanel1, ...
                         'String', '', ...
                         'Units', 'normalized', 'Position', [0.05, 0.20, 0.90, 0.60], ...
                         'FontSize', 22, 'FontWeight', 'bold', ...
                         'ForegroundColor', [1, 0.45, 0.45], ...
                         'BackgroundColor', [0.12 0.14 0.18]);

    % Panel 2: Lexicon Corrected Display
    hPanel2 = uipanel('Parent', fig, 'Title', ' Meaningful Dictionary Match ', ...
                      'FontSize', 11, 'ForegroundColor', [0.4 0.9 0.4], ...
                      'BackgroundColor', [0.12 0.14 0.18], ...
                      'Position', [0.53, 0.50, 0.42, 0.28]);

    hCorrText = uicontrol('Style', 'text', 'Parent', hPanel2, ...
                          'String', '...', ...
                          'Units', 'normalized', 'Position', [0.05, 0.20, 0.90, 0.60], ...
                          'FontSize', 22, 'FontWeight', 'bold', ...
                          'ForegroundColor', [0.4, 0.9, 0.4], ...
                          'BackgroundColor', [0.12 0.14 0.18]);

    % Panel 3: Transformation & Metrics Dashboard
    hPanel3 = uipanel('Parent', fig, 'Title', ' Transformation Metrics & Operations ', ...
                      'FontSize', 11, 'ForegroundColor', [0.9 0.9 0.9], ...
                      'BackgroundColor', [0.12 0.14 0.18], ...
                      'Position', [0.05, 0.08, 0.90, 0.38]);

    % Details Labels inside Panel 3
    uicontrol('Style', 'text', 'Parent', hPanel3, 'String', 'Levenshtein Distance:', ...
              'Units', 'normalized', 'Position', [0.05, 0.70, 0.30, 0.20], ...
              'FontSize', 11, 'ForegroundColor', [0.7 0.7 0.7], 'BackgroundColor', [0.12 0.14 0.18]);

    hDistVal = uicontrol('Style', 'text', 'Parent', hPanel3, 'String', '--', ...
                         'Units', 'normalized', 'Position', [0.35, 0.70, 0.15, 0.20], ...
                         'FontSize', 12, 'FontWeight', 'bold', 'ForegroundColor', [1 1 1], ...
                         'BackgroundColor', [0.12 0.14 0.18]);

    uicontrol('Style', 'text', 'Parent', hPanel3, 'String', 'Match Confidence:', ...
              'Units', 'normalized', 'Position', [0.55, 0.70, 0.25, 0.20], ...
              'FontSize', 11, 'ForegroundColor', [0.7 0.7 0.7], 'BackgroundColor', [0.12 0.14 0.18]);

    hConfVal = uicontrol('Style', 'text', 'Parent', hPanel3, 'String', '-- %', ...
                         'Units', 'normalized', 'Position', [0.80, 0.70, 0.15, 0.20], ...
                         'FontSize', 12, 'FontWeight', 'bold', 'ForegroundColor', [0.35, 0.78, 1.0], ...
                         'BackgroundColor', [0.12 0.14 0.18]);

    uicontrol('Style', 'text', 'Parent', hPanel3, 'String', 'Edit Operations:', ...
              'Units', 'normalized', 'Position', [0.05, 0.40, 0.30, 0.20], ...
              'FontSize', 11, 'ForegroundColor', [0.7 0.7 0.7], 'BackgroundColor', [0.12 0.14 0.18]);

    hOpsVal = uicontrol('Style', 'text', 'Parent', hPanel3, 'String', 'Calculating...', ...
                        'Units', 'normalized', 'Position', [0.35, 0.40, 0.60, 0.20], ...
                        'FontSize', 11, 'ForegroundColor', [0.9 0.9 0.9], 'BackgroundColor', [0.12 0.14 0.18]);

    hStatusStep = uicontrol('Style', 'text', 'Parent', hPanel3, 'String', 'Status: Initializing...', ...
                            'Units', 'normalized', 'Position', [0.05, 0.10, 0.90, 0.20], ...
                            'FontSize', 11, 'FontAngle', 'italic', 'ForegroundColor', [0.8 0.9 0.5], ...
                            'BackgroundColor', [0.12 0.14 0.18]);

    % ----------------------------------------------------
    % ANIMATION STEP 1: Typing out raw character output
    % ----------------------------------------------------
    raw_chars = cellstr(split(char(details.raw), ''));
    raw_chars = raw_chars(~cellfun('isempty', raw_chars));
    current_raw = '';

    for i = 1:length(raw_chars)
        current_raw = [current_raw raw_chars{i}];
        set(hRawText, 'String', current_raw);
        pause(0.25);
    end
    pause(0.5);

    % ----------------------------------------------------
    % ANIMATION STEP 2: Lexicon Searching
    % ----------------------------------------------------
    set(hStatus, 'String', 'Step 2: Searching Malayalam Lexicon & Computing Edit Distances...');
    set(hStatusStep, 'String', sprintf('Status: Checking dictionary against "%s"...', details.raw));

    for p = 1:5
        set(hCorrText, 'String', repmat('.', 1, p*2));
        pause(0.2);
    end
    pause(0.4);

    % ----------------------------------------------------
    % ANIMATION STEP 3: Revealing Match & Metrics
    % ----------------------------------------------------
    set(hStatus, 'String', 'Step 3: Morphing Raw Sequence into Meaningful Dictionary Match!');
    set(hCorrText, 'String', details.corrected);

    set(hDistVal, 'String', num2str(details.distance));
    set(hConfVal, 'String', sprintf('%.1f%%', details.confidence));

    ops_str = sprintf('Substitutions: %d | Insertions: %d | Deletions: %d', ...
                      details.ops.substitutions, details.ops.insertions, details.ops.deletions);
    set(hOpsVal, 'String', ops_str);

    if details.is_corrected
        set(hStatusStep, 'String', sprintf('✔ Transformation Complete: Corrected "%s" ➜ "%s"', ...
                                           details.raw, details.corrected));
    else
        set(hStatusStep, 'String', sprintf('✔ Exact Match Found: Word "%s" validated in dictionary.', details.raw));
    end
end
